name: GitHub Actions
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_SHA}

    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v3.1
      with:
        image: cnabio/signy-in-toto-verifier
        tag: ${{ steps.get_version.outputs.VERSION }}
        registry: docker.io
        dockerfile: Dockerfiles/in-toto-container.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, Test, Lint
      run: |
        export GOPATH=$HOME/go && export GOBIN=$(go env GOPATH)/bin && export PATH=$PATH:$GOPATH&& export PATH=$PATH:$GOBIN && mkdir -p $GOBIN

        make bootstrap build test lint
